services:
  api:
    container_name: coto.ventasAutos.Api
    build: .    
    ports:
      - "5003:5003"
    depends_on:
      - db
    environment:      
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=VentasAutomoviles;User Id=sa;Password=Password01!;TrustServerCertificate=true;
    networks:
      - coto_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: coto.ventasAutos.sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password01!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "Password01!", "-Q", "SELECT 1"]
      interval: 10s
      retries: 5
      start_period: 30s
    networks:
      - coto_network

networks:
  coto_network:
    driver: bridge

volumes:
  sqlserver_data:


