services:
  api:
    build: .
    ports:
       - "5000:5000"  # Exponer el puerto 5000
       - "5001:5001"  # Exponer el puerto 5001
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=VentasAutomoviles;User Id=sa;Password=Password01!;TrustServerCertificate=true;

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: test_sqlserver
    ports:
      - "1435:1433"
    environment:
      SA_PASSWORD: "Password01!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:

